# docker-compose.dev.yml
version: '3.8'

services:
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: neon-local-proxy
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      - ./.neon_local/:/tmp/.neon_local
      - ./.git/HEAD:/tmp/.git/HEAD:ro,consistent
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquistions-app-dev
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    volumes:
      - ./src:/app/src:cached
      - ./package.json:/app/package.json:ro
      - ./drizzle.config.js:/app/drizzle.config.js:ro
      - /app/node_modules
    depends_on:
      - neon-local
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
